### PR TITLE
Remove extra space after protocol name

### LINKED ISSUE #36: Remove extra space after protocol name in Mock class `inheritanceClause`
Current code generation:
```swift
class TestMock: Test , Verifiable {
```
Should be:
```swift
class TestMock: Test, Verifiable {
```

### PR DESCRIPTION
**Pull request by YeiHuynh**
Remove extra space after protocol name in Mock class inheritance Clause

### CODE REVIEW

**Comment by MetalheadSanya** [comment]
You have corrected the tests that check the result of running a macro. It is necessary to correct not only the tests, but also the macro code itself.

**Review by MetalheadSanya — CHANGES_REQUESTED** [review]
You have corrected the tests that check the result of running a macro. It is necessary to correct not only the tests, but also the macro code itself.

**Comment by YeiHuynh** [comment]
> You have corrected the tests that check the result of running a macro. It is necessary to correct not only the tests, but also the macro code itself.

Ok, I have corrected it in the macro code, please check again.

**Comment by MetalheadSanya** [comment]
> > You have corrected the tests that check the result of running a macro. It is necessary to correct not only the tests, but also the macro code itself.
> 
> Ok, I have corrected it in the macro code, please check again.

All files in `Tests/SwiftMockTests/Macro` just tests that validate macro code-generation.
Macro code is in `Sources/SwiftMockMacros`.

Mock class inheritanceClause generates in https://github.com/MetalheadSanya/swift-mock/blob/898c515f7abcfa972be8e41f311d158536537d25/Sources/SwiftMockMacros/SwiftMockMacro.swift#L32

**Comment by MetalheadSanya** [comment]
Build failed. You can check `Checks` tab for finding problems

**Pull request closed without merging**
